version: '3.1'

services:
    db:
        image: mongo
        container_name: mongoDB
        volumes:
            - './mongodb:/data/db'
        ports:
            - '27017:27017'
        restart: always
